# GitHub Pages configuration
plugins:
  - jekyll-redirect-from

# Exclude files from processing
exclude:
  - "*.json"
  - "*.xml"
  - "*.txt"
  - "*.md"

# Force UTF-8 encoding
encoding: utf-8

# Add cache headers via Jekyll
defaults:
  - scope:
      path: "_next/static"
    values:
      cache_control: "public, max-age=31536000, immutable"
  - scope:
      path: "*.js"
    values:
      cache_control: "public, max-age=31536000, immutable"
  - scope:
      path: "*.css"
    values:
      cache_control: "public, max-age=31536000, immutable"
