#!/usr/bin/env ts-node
/**
 * Script to split stadiumSections.ts into individual stadium files
 * This enables proper code splitting and reduces bundle size
 */

import * as fs from 'fs';
import * as path from 'path';

const SECTIONS_FILE = path.join(__dirname, '../src/data/stadiumSections.ts');
const OUTPUT_DIR = path.join(__dirname, '../src/data/sections-split');

interface StadiumSectionsData {
  stadiumId: string;
  sections: any[];
}

async function splitStadiumSections() {
  console.log('🔨 Starting stadium sections split...\n');

  // Read the original file
  const content = fs.readFileSync(SECTIONS_FILE, 'utf-8');

  // Extract the import statements
  const importMatch = content.match(/^import[\s\S]*?from.*?;/gm);
  const imports = importMatch ? importMatch.join('\n') : '';

  // Extract the type definitions
  const typeMatch = content.match(/export (type|interface) [\s\S]*?^}/gm);
  const types = typeMatch ? typeMatch.join('\n\n') : '';

  // Extract stadiumSections array
  const arrayMatch = content.match(/export const stadiumSections[\s\S]*?= \[([\s\S]*?)\];/);
  if (!arrayMatch) {
    console.error('❌ Could not find stadiumSections array');
    process.exit(1);
  }

  // Parse stadium objects (simplified - assumes each stadium starts with { stadiumId:)
  const stadiumPattern = /\{\s*stadiumId:\s*['"]([^'"]+)['"],\s*sections:\s*\[([\s\S]*?)\]\s*\}/g;
  const stadiums: Array<{ id: string; content: string }> = [];

  let match;
  while ((match = stadiumPattern.exec(arrayMatch[0])) !== null) {
    const stadiumId = match[1];
    const sectionsContent = match[2];

    stadiums.push({
      id: stadiumId,
      content: sectionsContent.trim()
    });
  }

  console.log(`Found ${stadiums.length} stadiums to split\n`);

  // Create output directory
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  // Write individual files
  let successCount = 0;
  let errorCount = 0;

  for (const stadium of stadiums) {
    try {
      const fileName = `${stadium.id}.ts`;
      const filePath = path.join(OUTPUT_DIR, fileName);

      const fileContent = `// Auto-generated stadium sections file for ${stadium.id}
// Generated by scripts/split-stadium-sections.ts

import { StadiumSection } from '../stadiumSections';

export const ${stadium.id}Sections: StadiumSection[] = [
  ${stadium.content}
];

export default ${stadium.id}Sections;
`;

      fs.writeFileSync(filePath, fileContent, 'utf-8');
      console.log(`✓ Created ${fileName}`);
      successCount++;
    } catch (error) {
      console.error(`✗ Error creating file for ${stadium.id}:`, error);
      errorCount++;
    }
  }

  // Create index file for type exports
  const indexContent = `// Auto-generated index file
// Generated by scripts/split-stadium-sections.ts

export * from '../stadiumSections'; // Export types only
`;

  fs.writeFileSync(path.join(OUTPUT_DIR, 'index.ts'), indexContent, 'utf-8');

  console.log('\n📊 Split Summary:');
  console.log(`   ✓ Success: ${successCount} files`);
  console.log(`   ✗ Errors: ${errorCount} files`);
  console.log(`   📁 Output: ${OUTPUT_DIR}\n`);

  if (successCount > 0) {
    console.log('✅ Stadium sections split complete!');
    console.log('\nNext steps:');
    console.log('1. Update stadiumLoader.ts to import from sections-split/');
    console.log('2. Run type checks: npm run type-check');
    console.log('3. Run build: npm run build');
  } else {
    console.log('❌ No files were created. Check the input file format.');
    process.exit(1);
  }
}

splitStadiumSections().catch(console.error);
